### PR TITLE
Update Packages for Flow and Typescript

### PR DESCRIPTION
**Pull request by danielnass**

### CODE REVIEW

**Review by brunodahora — APPROVED** [review]
:clap:

**Comment by gabrielreisn** [comment]
:clap:

**Comment by gabrielreisn** [comment]
@danielnass just keep in mind that since the repo doesn't have a CI/CD process configuration you'll need to change the package.json versions manually in order to deploy it to npm

**Comment by danielnass** [comment]
@gabrielreisn thank you to remind me 😄

**Pull request merged**
